default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: contactually_lite_development

test:
  <<: *default
  database: contactually_lite_test

production:
  <<: *default
  database: contactually_lite
