require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe ContactsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Contact. As you add validations to Contact, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryGirl.attributes_for :contact
  }

  let(:invalid_attributes) {
    {
      first_name: ''
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ContactsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      contact = Contact.create! valid_attributes
      get :index, {}, valid_session
      expect(response).to be_success
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      contact = Contact.create! valid_attributes
      get :show, {:id => contact.to_param}, valid_session
      expect(response).to be_success
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, {}, valid_session
      expect(response).to be_success
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      contact = Contact.create! valid_attributes
      get :edit, {:id => contact.to_param}, valid_session
      expect(response).to be_success
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Contact" do
        expect {
          post :create, {:contact => valid_attributes}, valid_session
        }.to change(Contact, :count).by(1)
      end

      it "redirects to the created contact" do
        post :create, {:contact => valid_attributes}, valid_session
        expect(response).to redirect_to(Contact.last)
      end

      context 'when company does not exist' do
        let(:company_attributes) { valid_attributes.merge(company_attributes: {name: Faker::Company.name})}

        it 'creates a new Company' do
          expect {
            post :create, {:contact => company_attributes}, valid_session
          }.to change(Company, :count).by(1)
        end
      end

      context 'when company exists' do
        let!(:company) { FactoryGirl.create(:company) }
        let(:company_attributes) { valid_attributes.merge(company_attributes: {name: company.name})}

        it 'creates a new contact' do
          expect {
            post :create, {:contact => company_attributes}, valid_session
          }.to change(Contact, :count).by(1)
        end

        it 'does not create a new Company' do
          expect {
            post :create, {:contact => company_attributes}, valid_session
          }.to_not change(Company, :count)
        end

        it 'associates the contact with the company' do
          post :create, {:contact => company_attributes}, valid_session

          expect(Contact.last.company).to eq company
        end
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, {:contact => invalid_attributes}, valid_session
        expect(response).to be_success
      end
    end
  end

  describe "PUT #update" do
    let!(:contact) { FactoryGirl.create(:contact) }

    context "with valid params" do
      let(:new_attributes) {
        {
          first_name: Faker::Name.first_name + 'new'
        }
      }

      it "updates the requested contact" do
        put :update, {:id => contact.to_param, :contact => new_attributes}, valid_session
        contact.reload
        expect(contact.first_name).to eq new_attributes[:first_name]
      end

      it "redirects to the contact" do
        put :update, {:id => contact.to_param, :contact => valid_attributes}, valid_session
        expect(response).to redirect_to(contact)
      end

      context 'when company does not exist' do
        let(:company_attributes) { new_attributes.merge(company_attributes: {name: Faker::Company.name})}

        it 'creates a new Company' do
          expect {
            put :update, {:id => contact.to_param, :contact => company_attributes}, valid_session
          }.to change(Company, :count).by(1)
        end
      end

      context 'when company exists' do
        let!(:company) { FactoryGirl.create(:company) }
        let(:company_attributes) { new_attributes.merge(company_attributes: {name: company.name})}

        it "updates the requested contact" do
          put :update, {:id => contact.to_param, :contact => company_attributes}, valid_session
          contact.reload
          expect(contact.first_name).to eq new_attributes[:first_name]
          expect(contact.company).to eq company
        end

        it 'does not create a new Company' do
          expect {
            put :update, {:id => contact.to_param, :contact => company_attributes}, valid_session
          }.to_not change(Company, :count)
        end
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        put :update, {:id => contact.to_param, :contact => invalid_attributes}, valid_session
        expect(response).to be_success
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested contact" do
      contact = Contact.create! valid_attributes
      expect {
        delete :destroy, {:id => contact.to_param}, valid_session
      }.to change(Contact, :count).by(-1)
    end

    it "redirects to the contacts list" do
      contact = Contact.create! valid_attributes
      delete :destroy, {:id => contact.to_param}, valid_session
      expect(response).to redirect_to(contacts_url)
    end
  end

end
